#!/bin/sh

ANDROID_ROOT="/opt/android-ndk" \
WITH_ARES=$ANDROID_ROOT/external/c-ares/jni/ \
TOOLCHAIN_VER="4.4.0" \
PLATFORM_VER="9" \
CROSS_COMPILE=arm-eabi- \
PATH=$ANDROID_ROOT/toolchains/arm-eabi-$TOOLCHAIN_VER/prebuilt/linux-x86/bin:$PATH \
CPPFLAGS="-I$ANDROID_ROOT/platforms/android-$PLATFORM_VER/arch-arm/usr/include -L$ANDROID_ROOT/toolchains/arm-eabi-$TOOLCHAIN_VER/prebuilt/linux-x86/lib/gcc/arm-eabi/$TOOLCHAIN_VER/lib -L$ANDROID_ROOT/platforms/android-$PLATFORM_VER/arch-arm/usr/lib " \
CFLAGS="-fno-exceptions -Wno-multichar -mthumb -mthumb-interwork -nostdlib -lc -ldl -lm " \
./configure CC=arm-eabi-gcc --host=arm-linux --disable-tftp --disable-sspi --disable-ipv6 --disable-ldaps --disable-ldap --disable-telnet --disable-pop3 --disable-ftp --without-ssl --disable-imap --disable-smtp --disable-pop3 --disable-rtsp --disable-ares --without-ca-bundle --disable-warnings --disable-manual --without-nss --enable-shared --with-zlib --without-random --enable-ares=$ANDROID_ROOT/external/c-ares/
